### Numpy:Package for Multidimensional array

In [1]:
import numpy as np

In [2]:
simple_list=[4,5,6]
np.array(simple_list)

array([4, 5, 6])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(5,56)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55])

In [6]:
np.arange(2,45,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44])

## whole no

In [9]:
np.arange(0,51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [12]:
np.arange(5,26,5)

array([ 5, 10, 15, 20, 25])

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.ones(4,float)

array([1., 1., 1., 1.])

In [21]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [25]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
np.eye((10),dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [30]:
np.random.rand(2,8)

array([[0.71048178, 0.01860742, 0.79148599, 0.04049348, 0.54353875,
        0.20356263, 0.64095134, 0.70271619],
       [0.62746371, 0.69848159, 0.67861437, 0.07455514, 0.90723148,
        0.5387311 , 0.10462616, 0.17560953]])

In [32]:
arr=np.random.rand(2,8)
arr

array([[0.68000577, 0.52613287, 0.51791239, 0.01870509, 0.83992902,
        0.31898775, 0.74706211, 0.35413497],
       [0.00619136, 0.39799026, 0.5861067 , 0.47010475, 0.00260306,
        0.92584346, 0.34858457, 0.55277166]])

In [34]:
np.random.randint(2,8)

7

In [36]:
np.random.randint(30,45,200)

array([31, 33, 38, 41, 34, 31, 31, 30, 39, 35, 32, 38, 39, 43, 39, 41, 43,
       33, 32, 44, 44, 34, 37, 35, 32, 37, 34, 39, 44, 36, 37, 38, 38, 33,
       44, 34, 43, 34, 32, 39, 30, 30, 31, 31, 37, 32, 41, 36, 30, 32, 31,
       36, 42, 43, 38, 42, 30, 41, 32, 33, 40, 43, 31, 36, 41, 31, 33, 39,
       31, 44, 30, 34, 35, 35, 43, 40, 39, 38, 35, 33, 39, 32, 30, 30, 34,
       34, 38, 41, 38, 33, 44, 41, 35, 43, 36, 42, 35, 33, 44, 37, 36, 34,
       36, 37, 43, 37, 32, 40, 33, 32, 43, 37, 38, 40, 32, 44, 38, 32, 32,
       41, 35, 44, 36, 35, 42, 36, 31, 39, 32, 31, 36, 36, 39, 33, 30, 31,
       30, 31, 38, 37, 31, 35, 31, 31, 30, 36, 40, 35, 41, 30, 41, 37, 35,
       35, 43, 31, 39, 42, 31, 30, 41, 36, 40, 36, 30, 38, 38, 35, 31, 30,
       43, 36, 40, 32, 40, 41, 31, 44, 44, 30, 35, 41, 33, 43, 41, 40, 34,
       34, 31, 41, 33, 37, 43, 30, 36, 37, 35, 33, 41, 42])

In [39]:
np.random.randint(1,5,8)

array([3, 3, 4, 2, 4, 1, 1, 1])

In [43]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
rand_array=np.random.randint(0,100,30)
rand_array

array([34, 45, 25, 79, 38, 27, 54, 64, 16, 75, 41, 82, 84, 45, 23, 93, 95,
       18, 57, 21, 97, 25,  6, 13,  3, 45, 33, 98, 19, 93])

In [46]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [50]:
rand_array.min()

1

In [57]:
rand_array.max()

99

In [51]:
rand_array.argmin()

31

In [58]:
rand_array.argmax()

25

In [59]:
a=np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [60]:
a.T

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [61]:
a=np.random.rand(4,5)
a

array([[0.27214002, 0.56232069, 0.48331537, 0.75928762, 0.15685999],
       [0.35171592, 0.3427324 , 0.31830619, 0.15039923, 0.30525832],
       [0.04477357, 0.26247701, 0.85112676, 0.0138674 , 0.86079414],
       [0.39371514, 0.02165357, 0.12772911, 0.29006036, 0.89091752]])

In [62]:
a.T

array([[0.27214002, 0.35171592, 0.04477357, 0.39371514],
       [0.56232069, 0.3427324 , 0.26247701, 0.02165357],
       [0.48331537, 0.31830619, 0.85112676, 0.12772911],
       [0.75928762, 0.15039923, 0.0138674 , 0.29006036],
       [0.15685999, 0.30525832, 0.86079414, 0.89091752]])

In [64]:
sample_array=np.arange(12,20)
sample_array

array([12, 13, 14, 15, 16, 17, 18, 19])

In [65]:
sample_array[3:5]

array([15, 16])

In [66]:
sample_array[1:5]=200
sample_array

array([ 12, 200, 200, 200, 200,  17,  18,  19])

In [72]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [73]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [74]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

subset_sample_array[:]=1001
subset_sample_array

In [75]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two-Dimensional array

In [76]:
import numpy as np

In [77]:
sample_matrix=np.array(([45,67,89],[23,34,57],[49,10,39],[93,57,43]))
sample_matrix

array([[45, 67, 89],
       [23, 34, 57],
       [49, 10, 39],
       [93, 57, 43]])

In [79]:
sample_matrix[0][2]

89

In [80]:
sample_matrix[2,:]

array([49, 10, 39])

In [81]:
sample_matrix[3]

array([93, 57, 43])

In [88]:
sample_matrix[:,(2,2)]

array([[89, 89],
       [57, 57],
       [39, 39],
       [43, 43]])

### Selection techniques

In [89]:
sample_array=np.arange(1,20)

In [90]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [91]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

# exponential

In [92]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [93]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [95]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [96]:
np.max(sample_array)


19

In [97]:
np.min(sample_array)

1

In [98]:
np.argmax(sample_array)

18

In [99]:
np.argmin(sample_array)

0

In [102]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [103]:
np.std(sample_array)

5.477225575051661

In [104]:
np.var(sample_array)

30.0

In [105]:
np.mean(sample_array)

10.0

In [108]:
array=np.random.randn(3,4)
array

array([[ 0.07595212, -1.35322475,  0.13731967, -1.30983168],
       [-0.99635927, -1.48531523, -0.27087599, -0.49706882],
       [-0.71764899, -1.57021588, -0.14922552,  0.48233695]])

In [109]:
np.round(array,decimals=2)

array([[ 0.08, -1.35,  0.14, -1.31],
       [-1.  , -1.49, -0.27, -0.5 ],
       [-0.72, -1.57, -0.15,  0.48]])

In [115]:
sports=np.array(['hockey','cricket','golf',' footbal'])
np.unique(sports)

array([' footbal', 'cricket', 'golf', 'hockey'], dtype='<U8')